source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HRDate_Example', :exclusive => true do
  pod 'HRDate', :path => '../'
end

target 'HRDate_Tests', :exclusive => true do
  pod 'HRDate', :path => '../'

  
end
